"""
OPS Signal Router - TensorGuardFlow Robotics Integrations

Routes inbound signals from robotics ops platforms to release safety actions.

Responsibilities:
1. Map InboundOpsSignal → action plan (rollback, freeze, quarantine, etc.)
2. Enforce route policy (allow_auto_rollback, require_verified_signature, etc.)
3. Write evidence timeline events
4. Emit outbound confirmation events back to originating tools
"""

import hashlib
import json
import time
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Callable

from tensorguard.integrations.connectors.robotics.schemas import (
    InboundOpsSignal,
    OutboundOpsEvent,
    EventPayload,
    ActionContext,
    EvidenceRefs,
    Severity,
    EventCategory,
    OutboundEventType,
    InboundSignalType,
    ActionType,
    SignalSource,
    DEFAULT_SIGNAL_ACTION_MAP,
    get_default_action_for_signal,
)


# =============================================================================
# ROUTE POLICY CONFIGURATION
# =============================================================================


@dataclass
class OpsSignalPolicy:
    """Policy configuration for handling ops signals on a route."""
    # Automation controls
    allow_auto_rollback: bool = True
    allow_auto_freeze: bool = True
    allow_auto_quarantine: bool = True
    require_verified_signature_for_automation: bool = True

    # Thresholds
    cooldown_window_sec: int = 300  # 5 minutes between auto-actions
    max_auto_actions_per_hour: int = 5

    # Signal type overrides
    signal_type_actions: Dict[str, ActionType] = field(default_factory=dict)

    # Severity overrides
    critical_always_freeze: bool = True
    warn_requires_investigation: bool = True

    def to_dict(self) -> Dict[str, Any]:
        return {
            "allow_auto_rollback": self.allow_auto_rollback,
            "allow_auto_freeze": self.allow_auto_freeze,
            "allow_auto_quarantine": self.allow_auto_quarantine,
            "require_verified_signature_for_automation": self.require_verified_signature_for_automation,
            "cooldown_window_sec": self.cooldown_window_sec,
            "max_auto_actions_per_hour": self.max_auto_actions_per_hour,
            "signal_type_actions": {
                k: v.value for k, v in self.signal_type_actions.items()
            },
            "critical_always_freeze": self.critical_always_freeze,
            "warn_requires_investigation": self.warn_requires_investigation,
        }


# =============================================================================
# ACTION RESULT
# =============================================================================


@dataclass
class ActionResult:
    """Result of executing an action."""
    success: bool
    action: ActionType
    message: str
    details: Dict[str, Any] = field(default_factory=dict)
    evidence_event_id: Optional[str] = None
    confirmation_event_id: Optional[str] = None


@dataclass
class RoutingDecision:
    """Decision made by the router."""
    signal_id: str
    route_key: str
    action: ActionType
    reason: str
    blocked: bool = False
    blocked_reason: Optional[str] = None
    cooldown_remaining_sec: Optional[int] = None


# =============================================================================
# EVIDENCE TIMELINE EVENTS
# =============================================================================


class EvidenceEventType(str, Enum):
    """Types of evidence events generated by the router."""
    OPS_SIGNAL_RECEIVED = "ops_signal_received"
    AUTO_ROLLBACK_TRIGGERED = "auto_rollback_triggered"
    AUTO_FREEZE_TRIGGERED = "auto_freeze_triggered"
    AUTO_QUARANTINE_TRIGGERED = "auto_quarantine_triggered"
    INVESTIGATION_OPENED = "investigation_opened"
    ACTION_BLOCKED_POLICY = "action_blocked_policy"
    ACTION_BLOCKED_COOLDOWN = "action_blocked_cooldown"
    ACTION_BLOCKED_SIGNATURE = "action_blocked_signature"
    SIGNAL_ACKNOWLEDGED = "signal_acknowledged"


@dataclass
class EvidenceTimelineEvent:
    """Event for the evidence timeline."""
    event_id: str
    event_type: EvidenceEventType
    timestamp: str
    route_key: str
    signal_id: Optional[str]
    action_taken: Optional[ActionType]
    details: Dict[str, Any]
    signature: Optional[str] = None


# =============================================================================
# COOLDOWN TRACKER
# =============================================================================


class CooldownTracker:
    """Tracks cooldowns to prevent action thrashing."""

    def __init__(self):
        self._last_actions: Dict[str, float] = {}  # route_key -> timestamp
        self._action_counts: Dict[str, List[float]] = {}  # route_key -> [timestamps]

    def check_cooldown(
        self,
        route_key: str,
        cooldown_sec: int,
    ) -> tuple[bool, int]:
        """
        Check if cooldown has expired.

        Returns:
            (is_allowed, remaining_seconds)
        """
        last_action = self._last_actions.get(route_key)
        if not last_action:
            return True, 0

        elapsed = time.time() - last_action
        if elapsed >= cooldown_sec:
            return True, 0

        return False, int(cooldown_sec - elapsed)

    def check_rate_limit(
        self,
        route_key: str,
        max_per_hour: int,
    ) -> bool:
        """Check if rate limit allows another action."""
        if route_key not in self._action_counts:
            return True

        # Remove actions older than 1 hour
        one_hour_ago = time.time() - 3600
        self._action_counts[route_key] = [
            ts for ts in self._action_counts[route_key]
            if ts > one_hour_ago
        ]

        return len(self._action_counts[route_key]) < max_per_hour

    def record_action(self, route_key: str):
        """Record that an action was taken."""
        now = time.time()
        self._last_actions[route_key] = now

        if route_key not in self._action_counts:
            self._action_counts[route_key] = []
        self._action_counts[route_key].append(now)

    def clear(self, route_key: Optional[str] = None):
        """Clear cooldown state."""
        if route_key:
            self._last_actions.pop(route_key, None)
            self._action_counts.pop(route_key, None)
        else:
            self._last_actions.clear()
            self._action_counts.clear()


# =============================================================================
# OPS SIGNAL ROUTER
# =============================================================================


class OpsSignalRouter:
    """
    Routes inbound ops signals to release safety actions.

    The router:
    1. Receives normalized InboundOpsSignal from connectors
    2. Looks up route policy
    3. Determines appropriate action based on signal type and policy
    4. Executes action (via callbacks)
    5. Records evidence timeline events
    6. Emits confirmation events back to source platform
    """

    def __init__(
        self,
        # Callbacks for actions
        on_rollback: Optional[Callable[[str, str, Dict], bool]] = None,
        on_freeze: Optional[Callable[[str, Dict], bool]] = None,
        on_unfreeze: Optional[Callable[[str, Dict], bool]] = None,
        on_quarantine: Optional[Callable[[str, str, Dict], bool]] = None,
        on_investigation: Optional[Callable[[str, str, Dict], str]] = None,
        # Callback for outbound events
        on_outbound_event: Optional[Callable[[OutboundOpsEvent, str], None]] = None,
        # Policy lookup
        get_route_policy: Optional[Callable[[str], Optional[OpsSignalPolicy]]] = None,
    ):
        self._on_rollback = on_rollback
        self._on_freeze = on_freeze
        self._on_unfreeze = on_unfreeze
        self._on_quarantine = on_quarantine
        self._on_investigation = on_investigation
        self._on_outbound_event = on_outbound_event
        self._get_route_policy = get_route_policy

        self._cooldown_tracker = CooldownTracker()
        self._evidence_events: List[EvidenceTimelineEvent] = []
        self._processed_signals: Dict[str, RoutingDecision] = {}

    # -------------------------------------------------------------------------
    # MAIN ROUTING LOGIC
    # -------------------------------------------------------------------------

    async def route_signal(
        self,
        signal: InboundOpsSignal,
        force_action: Optional[ActionType] = None,
    ) -> ActionResult:
        """
        Route an inbound signal to appropriate action.

        Args:
            signal: The normalized inbound signal
            force_action: Optional action to force (bypasses policy)

        Returns:
            ActionResult with outcome
        """
        # Record signal received
        self._record_evidence_event(
            EvidenceEventType.OPS_SIGNAL_RECEIVED,
            signal.route_key,
            signal.signal_id,
            None,
            {
                "source": signal.source.value,
                "type": signal.type.value,
                "severity": signal.severity.value,
                "auth_verified": signal.auth.verified,
            },
        )

        # Get route policy
        policy = self._get_policy(signal.route_key)

        # Determine action
        if force_action:
            action = force_action
            reason = "Forced by caller"
        else:
            action = self._determine_action(signal, policy)
            reason = f"Signal type {signal.type.value} maps to {action.value}"

        # Check if action is allowed
        decision = self._check_policy_allows(signal, action, policy)
        self._processed_signals[signal.signal_id] = decision

        if decision.blocked:
            self._record_evidence_event(
                EvidenceEventType.ACTION_BLOCKED_POLICY
                if "policy" in (decision.blocked_reason or "")
                else EvidenceEventType.ACTION_BLOCKED_COOLDOWN
                if "cooldown" in (decision.blocked_reason or "")
                else EvidenceEventType.ACTION_BLOCKED_SIGNATURE,
                signal.route_key,
                signal.signal_id,
                action,
                {
                    "blocked_reason": decision.blocked_reason,
                    "cooldown_remaining": decision.cooldown_remaining_sec,
                },
            )

            return ActionResult(
                success=False,
                action=action,
                message=f"Action blocked: {decision.blocked_reason}",
                details={"decision": decision.__dict__},
            )

        # Execute action
        result = await self._execute_action(signal, action, policy)

        # Emit confirmation event
        await self._emit_confirmation(signal, action, result)

        return result

    def _get_policy(self, route_key: str) -> OpsSignalPolicy:
        """Get policy for route, or return default."""
        if self._get_route_policy:
            policy = self._get_route_policy(route_key)
            if policy:
                return policy
        return OpsSignalPolicy()

    def _determine_action(
        self,
        signal: InboundOpsSignal,
        policy: OpsSignalPolicy,
    ) -> ActionType:
        """Determine the action to take based on signal and policy."""
        # Check policy overrides first
        if signal.type.value in policy.signal_type_actions:
            return policy.signal_type_actions[signal.type.value]

        # Use default mapping
        action = get_default_action_for_signal(signal.type, signal.severity)

        # Apply severity rules
        if signal.severity == Severity.CRITICAL and policy.critical_always_freeze:
            if action == ActionType.OPEN_INVESTIGATION:
                action = ActionType.FREEZE_ROUTE

        return action

    def _check_policy_allows(
        self,
        signal: InboundOpsSignal,
        action: ActionType,
        policy: OpsSignalPolicy,
    ) -> RoutingDecision:
        """Check if policy allows the action."""
        route_key = signal.route_key

        # Check signature requirement
        if policy.require_verified_signature_for_automation:
            if action in (ActionType.ROLLBACK_ROUTE, ActionType.QUARANTINE_ADAPTER):
                if not signal.auth.verified:
                    return RoutingDecision(
                        signal_id=signal.signal_id,
                        route_key=route_key,
                        action=action,
                        reason="Signature verification required",
                        blocked=True,
                        blocked_reason="Signature not verified for automated critical action",
                    )

        # Check action-specific policy
        if action == ActionType.ROLLBACK_ROUTE and not policy.allow_auto_rollback:
            return RoutingDecision(
                signal_id=signal.signal_id,
                route_key=route_key,
                action=action,
                reason="Auto-rollback disabled by policy",
                blocked=True,
                blocked_reason="allow_auto_rollback=false in route policy",
            )

        if action == ActionType.FREEZE_ROUTE and not policy.allow_auto_freeze:
            return RoutingDecision(
                signal_id=signal.signal_id,
                route_key=route_key,
                action=action,
                reason="Auto-freeze disabled by policy",
                blocked=True,
                blocked_reason="allow_auto_freeze=false in route policy",
            )

        if action == ActionType.QUARANTINE_ADAPTER and not policy.allow_auto_quarantine:
            return RoutingDecision(
                signal_id=signal.signal_id,
                route_key=route_key,
                action=action,
                reason="Auto-quarantine disabled by policy",
                blocked=True,
                blocked_reason="allow_auto_quarantine=false in route policy",
            )

        # Check cooldown
        is_allowed, remaining = self._cooldown_tracker.check_cooldown(
            route_key, policy.cooldown_window_sec
        )
        if not is_allowed:
            return RoutingDecision(
                signal_id=signal.signal_id,
                route_key=route_key,
                action=action,
                reason="Cooldown active",
                blocked=True,
                blocked_reason=f"Cooldown: {remaining}s remaining",
                cooldown_remaining_sec=remaining,
            )

        # Check rate limit
        if not self._cooldown_tracker.check_rate_limit(
            route_key, policy.max_auto_actions_per_hour
        ):
            return RoutingDecision(
                signal_id=signal.signal_id,
                route_key=route_key,
                action=action,
                reason="Rate limit exceeded",
                blocked=True,
                blocked_reason=f"Max {policy.max_auto_actions_per_hour} actions/hour exceeded",
            )

        return RoutingDecision(
            signal_id=signal.signal_id,
            route_key=route_key,
            action=action,
            reason=f"Policy allows {action.value}",
            blocked=False,
        )

    async def _execute_action(
        self,
        signal: InboundOpsSignal,
        action: ActionType,
        policy: OpsSignalPolicy,
    ) -> ActionResult:
        """Execute the determined action."""
        route_key = signal.route_key
        context = {
            "signal_id": signal.signal_id,
            "source": signal.source.value,
            "severity": signal.severity.value,
            "reason": signal.payload.normalized.operator_notes or f"Signal: {signal.type.value}",
        }

        # Record cooldown
        if action in (
            ActionType.ROLLBACK_ROUTE,
            ActionType.FREEZE_ROUTE,
            ActionType.QUARANTINE_ADAPTER,
        ):
            self._cooldown_tracker.record_action(route_key)

        # Execute based on action type
        if action == ActionType.ROLLBACK_ROUTE:
            return await self._execute_rollback(signal, context)

        elif action == ActionType.FREEZE_ROUTE:
            return await self._execute_freeze(signal, context)

        elif action == ActionType.UNFREEZE_ROUTE:
            return await self._execute_unfreeze(signal, context)

        elif action == ActionType.QUARANTINE_ADAPTER:
            return await self._execute_quarantine(signal, context)

        elif action == ActionType.OPEN_INVESTIGATION:
            return await self._execute_investigation(signal, context)

        elif action == ActionType.ACKNOWLEDGE:
            self._record_evidence_event(
                EvidenceEventType.SIGNAL_ACKNOWLEDGED,
                route_key,
                signal.signal_id,
                action,
                context,
            )
            return ActionResult(
                success=True,
                action=action,
                message="Signal acknowledged",
            )

        else:
            return ActionResult(
                success=True,
                action=ActionType.NO_ACTION,
                message="No action required",
            )

    async def _execute_rollback(
        self,
        signal: InboundOpsSignal,
        context: Dict[str, Any],
    ) -> ActionResult:
        """Execute rollback action."""
        route_key = signal.route_key

        # Get current adapter (would come from registry in production)
        current_adapter_id = context.get("current_adapter_id", "unknown")
        rollback_target = context.get("rollback_target", "previous_stable")

        if self._on_rollback:
            success = self._on_rollback(route_key, rollback_target, context)
        else:
            # Simulate success
            success = True

        evidence_id = self._record_evidence_event(
            EvidenceEventType.AUTO_ROLLBACK_TRIGGERED,
            route_key,
            signal.signal_id,
            ActionType.ROLLBACK_ROUTE,
            {
                **context,
                "previous_adapter_id": current_adapter_id,
                "rollback_target": rollback_target,
            },
        )

        return ActionResult(
            success=success,
            action=ActionType.ROLLBACK_ROUTE,
            message=f"Rollback {'executed' if success else 'failed'} for {route_key}",
            details={
                "rollback_target": rollback_target,
                "previous_adapter_id": current_adapter_id,
            },
            evidence_event_id=evidence_id,
        )

    async def _execute_freeze(
        self,
        signal: InboundOpsSignal,
        context: Dict[str, Any],
    ) -> ActionResult:
        """Execute freeze action."""
        route_key = signal.route_key

        if self._on_freeze:
            success = self._on_freeze(route_key, context)
        else:
            success = True

        evidence_id = self._record_evidence_event(
            EvidenceEventType.AUTO_FREEZE_TRIGGERED,
            route_key,
            signal.signal_id,
            ActionType.FREEZE_ROUTE,
            context,
        )

        return ActionResult(
            success=success,
            action=ActionType.FREEZE_ROUTE,
            message=f"Route {route_key} {'frozen' if success else 'freeze failed'}",
            evidence_event_id=evidence_id,
        )

    async def _execute_unfreeze(
        self,
        signal: InboundOpsSignal,
        context: Dict[str, Any],
    ) -> ActionResult:
        """Execute unfreeze action."""
        route_key = signal.route_key

        if self._on_unfreeze:
            success = self._on_unfreeze(route_key, context)
        else:
            success = True

        return ActionResult(
            success=success,
            action=ActionType.UNFREEZE_ROUTE,
            message=f"Route {route_key} {'unfrozen' if success else 'unfreeze failed'}",
        )

    async def _execute_quarantine(
        self,
        signal: InboundOpsSignal,
        context: Dict[str, Any],
    ) -> ActionResult:
        """Execute quarantine action."""
        route_key = signal.route_key
        adapter_id = context.get("adapter_id", "current")

        if self._on_quarantine:
            success = self._on_quarantine(route_key, adapter_id, context)
        else:
            success = True

        evidence_id = self._record_evidence_event(
            EvidenceEventType.AUTO_QUARANTINE_TRIGGERED,
            route_key,
            signal.signal_id,
            ActionType.QUARANTINE_ADAPTER,
            {**context, "adapter_id": adapter_id},
        )

        return ActionResult(
            success=success,
            action=ActionType.QUARANTINE_ADAPTER,
            message=f"Adapter {adapter_id} {'quarantined' if success else 'quarantine failed'}",
            details={"adapter_id": adapter_id},
            evidence_event_id=evidence_id,
        )

    async def _execute_investigation(
        self,
        signal: InboundOpsSignal,
        context: Dict[str, Any],
    ) -> ActionResult:
        """Open an investigation."""
        route_key = signal.route_key

        if self._on_investigation:
            investigation_id = self._on_investigation(route_key, signal.signal_id, context)
        else:
            investigation_id = f"inv_{hashlib.sha256(signal.signal_id.encode()).hexdigest()[:12]}"

        evidence_id = self._record_evidence_event(
            EvidenceEventType.INVESTIGATION_OPENED,
            route_key,
            signal.signal_id,
            ActionType.OPEN_INVESTIGATION,
            {**context, "investigation_id": investigation_id},
        )

        return ActionResult(
            success=True,
            action=ActionType.OPEN_INVESTIGATION,
            message=f"Investigation opened: {investigation_id}",
            details={"investigation_id": investigation_id},
            evidence_event_id=evidence_id,
        )

    async def _emit_confirmation(
        self,
        signal: InboundOpsSignal,
        action: ActionType,
        result: ActionResult,
    ):
        """Emit confirmation event back to source platform."""
        if not self._on_outbound_event:
            return

        # Determine event type based on action
        event_type_map = {
            ActionType.ROLLBACK_ROUTE: OutboundEventType.ROLLBACK,
            ActionType.FREEZE_ROUTE: OutboundEventType.ROUTE_FROZEN,
            ActionType.UNFREEZE_ROUTE: OutboundEventType.ROUTE_UNFROZEN,
            ActionType.QUARANTINE_ADAPTER: OutboundEventType.ADAPTER_QUARANTINED,
        }

        event_type = event_type_map.get(action, OutboundEventType.INTEGRATION_HEALTH_CHANGED)

        event = OutboundOpsEvent(
            tenant_id=signal.tenant_id or "default",
            route_key=signal.route_key,
            severity=Severity.INFO if result.success else Severity.WARN,
            category=EventCategory.RELEASE,
            type=event_type,
            summary=result.message,
            payload=EventPayload(
                action_context=ActionContext(
                    triggered_by="ops_signal",
                    reason=result.message,
                    signal_id=signal.signal_id,
                ),
            ),
        )

        # Send to source platform
        provider = signal.source.value.lower()
        self._on_outbound_event(event, provider)

        result.confirmation_event_id = event.event_id

    def _record_evidence_event(
        self,
        event_type: EvidenceEventType,
        route_key: str,
        signal_id: Optional[str],
        action: Optional[ActionType],
        details: Dict[str, Any],
    ) -> str:
        """Record an evidence timeline event."""
        event_id = f"evt_{hashlib.sha256(f'{route_key}:{datetime.utcnow().isoformat()}'.encode()).hexdigest()[:12]}"

        event = EvidenceTimelineEvent(
            event_id=event_id,
            event_type=event_type,
            timestamp=datetime.utcnow().isoformat() + "Z",
            route_key=route_key,
            signal_id=signal_id,
            action_taken=action,
            details=details,
        )

        self._evidence_events.append(event)

        # Keep bounded size
        if len(self._evidence_events) > 1000:
            self._evidence_events = self._evidence_events[-1000:]

        return event_id

    # -------------------------------------------------------------------------
    # QUERY METHODS
    # -------------------------------------------------------------------------

    def get_evidence_events(
        self,
        route_key: Optional[str] = None,
        limit: int = 50,
    ) -> List[EvidenceTimelineEvent]:
        """Get recent evidence events."""
        events = self._evidence_events

        if route_key:
            events = [e for e in events if e.route_key == route_key]

        return events[-limit:]

    def get_processed_signals(
        self,
        route_key: Optional[str] = None,
    ) -> Dict[str, RoutingDecision]:
        """Get processed signal decisions."""
        if route_key:
            return {
                k: v for k, v in self._processed_signals.items()
                if v.route_key == route_key
            }
        return self._processed_signals

    def get_action_mapping_table(self) -> Dict[str, str]:
        """Get the signal type to action mapping table."""
        return {
            signal_type.value: action.value
            for signal_type, action in DEFAULT_SIGNAL_ACTION_MAP.items()
        }

    def clear_cooldowns(self, route_key: Optional[str] = None):
        """Clear cooldown state (admin operation)."""
        self._cooldown_tracker.clear(route_key)
