"""
Cloud training job exporters.

These exporters generate job specifications for cloud ML platforms.
All exporters are "export-only" by default - they do not submit jobs to cloud platforms.
"""

import json
from datetime import datetime
from typing import Any, Dict, List, Optional
import yaml

from tensorguard.integrations.framework.contracts import ExportArtifact


class BaseExporter:
    """Base class for all exporters."""

    def __init__(self, config: Dict[str, Any]):
        self.config = config

    def validate_context(self, context: Dict[str, Any]) -> List[str]:
        """Validate export context. Returns list of errors."""
        errors = []
        if not context.get("route_key"):
            errors.append("route_key is required in context")
        return errors

    def export(self, context: Dict[str, Any]) -> List[ExportArtifact]:
        """Export artifacts. Override in subclasses."""
        raise NotImplementedError


class SageMakerExporter(BaseExporter):
    """Exporter for AWS SageMaker training jobs."""

    def validate_context(self, context: Dict[str, Any]) -> List[str]:
        """Validate SageMaker export context."""
        errors = super().validate_context(context)

        # Check required config
        if not self.config.get("role_arn"):
            errors.append("role_arn is required in config")
        if not self.config.get("training_image"):
            errors.append("training_image is required in config")
        if not self.config.get("data_s3_uri"):
            errors.append("data_s3_uri is required in config")
        if not self.config.get("output_s3_uri"):
            errors.append("output_s3_uri is required in config")

        return errors

    def export(self, context: Dict[str, Any]) -> List[ExportArtifact]:
        """Export SageMaker training job specification."""
        errors = self.validate_context(context)
        if errors:
            raise ValueError(f"Invalid context: {errors}")

        route_key = context["route_key"]
        run_id = context.get("run_id", datetime.utcnow().strftime("%Y%m%d%H%M%S"))
        training_config = context.get("training_config", {})

        # Main training job spec
        job_spec = {
            "TrainingJobName": f"tgf-{route_key}-{run_id}"[:63],
            "AlgorithmSpecification": {
                "TrainingImage": self.config["training_image"],
                "TrainingInputMode": "File",
            },
            "RoleArn": self.config["role_arn"],
            "InputDataConfig": [
                {
                    "ChannelName": "training",
                    "DataSource": {
                        "S3DataSource": {
                            "S3DataType": "S3Prefix",
                            "S3Uri": self.config["data_s3_uri"],
                            "S3DataDistributionType": "FullyReplicated",
                        }
                    },
                }
            ],
            "OutputDataConfig": {
                "S3OutputPath": self.config["output_s3_uri"],
            },
            "ResourceConfig": {
                "InstanceType": self.config.get("instance_type", "ml.g5.xlarge"),
                "InstanceCount": self.config.get("instance_count", 1),
                "VolumeSizeInGB": self.config.get("volume_size_gb", 100),
            },
            "StoppingCondition": {
                "MaxRuntimeInSeconds": self.config.get("max_runtime_seconds", 86400),
            },
            "HyperParameters": {
                "tgf_route_key": route_key,
                "tgf_run_id": run_id,
                **{k: str(v) for k, v in training_config.items()},
            },
            "Tags": [
                {"Key": "tgf:managed", "Value": "true"},
                {"Key": "tgf:route-key", "Value": route_key},
            ],
        }

        # Add VPC config if specified
        if self.config.get("vpc_config"):
            job_spec["VpcConfig"] = self.config["vpc_config"]

        # Add network isolation if specified
        if self.config.get("enable_network_isolation"):
            job_spec["EnableNetworkIsolation"] = True

        artifacts = [
            ExportArtifact(
                name="sagemaker-training-job.json",
                content=json.dumps(job_spec, indent=2),
                artifact_type="json",
                metadata={
                    "job_name": job_spec["TrainingJobName"],
                    "instance_type": job_spec["ResourceConfig"]["InstanceType"],
                },
            )
        ]

        # Add CLI script
        cli_script = f'''#!/bin/bash
# SageMaker Training Job Submission Script
# Generated by TensorGuardFlow

set -e

JOB_SPEC="sagemaker-training-job.json"

echo "Submitting SageMaker training job..."
aws sagemaker create-training-job --cli-input-json file://$JOB_SPEC

echo "Job submitted: {job_spec["TrainingJobName"]}"
echo "Monitor with: aws sagemaker describe-training-job --training-job-name {job_spec["TrainingJobName"]}"
'''

        artifacts.append(
            ExportArtifact(
                name="submit-job.sh",
                content=cli_script,
                artifact_type="sh",
            )
        )

        # Add README
        readme = f'''# SageMaker Training Job Export

## Generated
{datetime.utcnow().isoformat()}

## Route
{route_key}

## Files
- `sagemaker-training-job.json` - CreateTrainingJob API input
- `submit-job.sh` - CLI submission script

## Submit Job

```bash
# Using AWS CLI
aws sagemaker create-training-job --cli-input-json file://sagemaker-training-job.json

# Or use the script
chmod +x submit-job.sh
./submit-job.sh
```

## Monitor Job

```bash
aws sagemaker describe-training-job --training-job-name {job_spec["TrainingJobName"]}
```

## Note
This export was generated by TensorGuardFlow.
Remote submission is disabled by default (TG_ENABLE_REMOTE_SUBMIT=false).
'''

        artifacts.append(
            ExportArtifact(
                name="README.md",
                content=readme,
                artifact_type="md",
            )
        )

        return artifacts


class VertexAIExporter(BaseExporter):
    """Exporter for Google Vertex AI custom jobs."""

    def validate_context(self, context: Dict[str, Any]) -> List[str]:
        """Validate Vertex AI export context."""
        errors = super().validate_context(context)

        if not self.config.get("project_id"):
            errors.append("project_id is required in config")
        if not self.config.get("training_image"):
            errors.append("training_image is required in config")

        return errors

    def export(self, context: Dict[str, Any]) -> List[ExportArtifact]:
        """Export Vertex AI custom job specification."""
        errors = self.validate_context(context)
        if errors:
            raise ValueError(f"Invalid context: {errors}")

        route_key = context["route_key"]
        run_id = context.get("run_id", datetime.utcnow().strftime("%Y%m%d%H%M%S"))
        training_config = context.get("training_config", {})

        job_spec = {
            "displayName": f"tgf-{route_key}-{run_id}",
            "jobSpec": {
                "workerPoolSpecs": [
                    {
                        "machineSpec": {
                            "machineType": self.config.get("machine_type", "n1-standard-8"),
                            "acceleratorType": self.config.get("accelerator_type", "NVIDIA_TESLA_V100"),
                            "acceleratorCount": self.config.get("accelerator_count", 1),
                        },
                        "replicaCount": 1,
                        "containerSpec": {
                            "imageUri": self.config["training_image"],
                            "env": [
                                {"name": "TGF_RUN_ID", "value": run_id},
                                {"name": "TGF_ROUTE_KEY", "value": route_key},
                            ] + [
                                {"name": k.upper(), "value": str(v)}
                                for k, v in training_config.items()
                            ],
                        },
                    }
                ],
            },
            "labels": {
                "tgf-managed": "true",
                "tgf-route-key": route_key.replace("_", "-"),
            },
        }

        artifacts = [
            ExportArtifact(
                name="vertex-custom-job.json",
                content=json.dumps(job_spec, indent=2),
                artifact_type="json",
                metadata={"display_name": job_spec["displayName"]},
            )
        ]

        # Add gcloud CLI script
        project_id = self.config["project_id"]
        location = self.config.get("location", "us-central1")

        cli_script = f'''#!/bin/bash
# Vertex AI Custom Job Submission Script
# Generated by TensorGuardFlow

set -e

PROJECT_ID="{project_id}"
LOCATION="{location}"
JOB_SPEC="vertex-custom-job.json"

echo "Submitting Vertex AI custom job..."
gcloud ai custom-jobs create \\
    --project=$PROJECT_ID \\
    --region=$LOCATION \\
    --display-name="{job_spec["displayName"]}" \\
    --config=$JOB_SPEC

echo "Job submitted. Monitor in Cloud Console."
'''

        artifacts.append(
            ExportArtifact(
                name="submit-job.sh",
                content=cli_script,
                artifact_type="sh",
            )
        )

        return artifacts


class AzureMLExporter(BaseExporter):
    """Exporter for Azure Machine Learning jobs."""

    def validate_context(self, context: Dict[str, Any]) -> List[str]:
        """Validate Azure ML export context."""
        errors = super().validate_context(context)

        if not self.config.get("workspace_name"):
            errors.append("workspace_name is required in config")
        if not self.config.get("compute_target"):
            errors.append("compute_target is required in config")

        return errors

    def export(self, context: Dict[str, Any]) -> List[ExportArtifact]:
        """Export Azure ML job specification."""
        errors = self.validate_context(context)
        if errors:
            raise ValueError(f"Invalid context: {errors}")

        route_key = context["route_key"]
        run_id = context.get("run_id", datetime.utcnow().strftime("%Y%m%d%H%M%S"))
        training_config = context.get("training_config", {})

        job_spec = {
            "$schema": "https://azuremlschemas.azureedge.net/latest/commandJob.schema.json",
            "type": "command",
            "display_name": f"tgf-{route_key}-{run_id}",
            "experiment_name": f"tgf-{route_key}",
            "compute": f"azureml:{self.config['compute_target']}",
            "environment": self.config.get("environment_name", "AzureML-pytorch-1.13-cuda11.7-cudnn8-devel"),
            "code": self.config.get("code_path", "./src"),
            "command": self.config.get("command", "python train.py"),
            "inputs": {
                "data": {
                    "type": "uri_folder",
                    "path": self.config.get("data_uri", ""),
                },
            },
            "outputs": {
                "model": {
                    "type": "uri_folder",
                    "path": self.config.get("output_uri", ""),
                },
            },
            "environment_variables": {
                "TGF_RUN_ID": run_id,
                "TGF_ROUTE_KEY": route_key,
                **{k.upper(): str(v) for k, v in training_config.items()},
            },
            "tags": {
                "tgf:managed": "true",
                "tgf:route-key": route_key,
            },
        }

        artifacts = [
            ExportArtifact(
                name="azureml-job.yaml",
                content=yaml.dump(job_spec, default_flow_style=False),
                artifact_type="yaml",
                metadata={"display_name": job_spec["display_name"]},
            )
        ]

        # Add Azure CLI script
        cli_script = f'''#!/bin/bash
# Azure ML Job Submission Script
# Generated by TensorGuardFlow

set -e

WORKSPACE="{self.config['workspace_name']}"
RESOURCE_GROUP="{self.config.get('resource_group', 'your-resource-group')}"
JOB_SPEC="azureml-job.yaml"

echo "Submitting Azure ML job..."
az ml job create \\
    --file $JOB_SPEC \\
    --workspace-name $WORKSPACE \\
    --resource-group $RESOURCE_GROUP

echo "Job submitted. Monitor in Azure Portal."
'''

        artifacts.append(
            ExportArtifact(
                name="submit-job.sh",
                content=cli_script,
                artifact_type="sh",
            )
        )

        return artifacts


class DatabricksExporter(BaseExporter):
    """Exporter for Databricks jobs."""

    def validate_context(self, context: Dict[str, Any]) -> List[str]:
        """Validate Databricks export context."""
        errors = super().validate_context(context)

        if not self.config.get("workspace_url"):
            errors.append("workspace_url is required in config")

        return errors

    def export(self, context: Dict[str, Any]) -> List[ExportArtifact]:
        """Export Databricks job specification."""
        errors = self.validate_context(context)
        if errors:
            raise ValueError(f"Invalid context: {errors}")

        route_key = context["route_key"]
        run_id = context.get("run_id", datetime.utcnow().strftime("%Y%m%d%H%M%S"))
        training_config = context.get("training_config", {})

        job_spec = {
            "name": f"tgf-{route_key}-{run_id}",
            "tags": {
                "tgf_managed": "true",
                "tgf_route_key": route_key,
            },
        }

        # Add cluster configuration
        if self.config.get("cluster_id"):
            job_spec["existing_cluster_id"] = self.config["cluster_id"]
        elif self.config.get("new_cluster"):
            job_spec["new_cluster"] = self.config["new_cluster"]
        else:
            job_spec["new_cluster"] = {
                "spark_version": "13.3.x-gpu-ml-scala2.12",
                "node_type_id": "Standard_NC6s_v3",
                "num_workers": 0,
                "spark_conf": {
                    "spark.databricks.delta.preview.enabled": "true",
                },
            }

        # Add task configuration
        if self.config.get("notebook_path"):
            job_spec["notebook_task"] = {
                "notebook_path": self.config["notebook_path"],
                "base_parameters": {
                    "tgf_run_id": run_id,
                    "tgf_route_key": route_key,
                    **{k: str(v) for k, v in training_config.items()},
                },
            }
        elif self.config.get("python_file"):
            job_spec["spark_python_task"] = {
                "python_file": self.config["python_file"],
                "parameters": [
                    f"--tgf-run-id={run_id}",
                    f"--tgf-route-key={route_key}",
                ] + [f"--{k}={v}" for k, v in training_config.items()],
            }

        artifacts = [
            ExportArtifact(
                name="databricks-job.json",
                content=json.dumps(job_spec, indent=2),
                artifact_type="json",
                metadata={"job_name": job_spec["name"]},
            )
        ]

        # Add Databricks CLI script
        workspace_url = self.config["workspace_url"]

        cli_script = f'''#!/bin/bash
# Databricks Job Submission Script
# Generated by TensorGuardFlow

set -e

WORKSPACE_URL="{workspace_url}"
JOB_SPEC="databricks-job.json"

echo "Submitting Databricks job..."

# Create job
JOB_ID=$(databricks jobs create --json-file $JOB_SPEC | jq -r '.job_id')
echo "Created job with ID: $JOB_ID"

# Run job
RUN_ID=$(databricks jobs run-now --job-id $JOB_ID | jq -r '.run_id')
echo "Started run with ID: $RUN_ID"

echo "Monitor at: $WORKSPACE_URL/#job/$JOB_ID/run/$RUN_ID"
'''

        artifacts.append(
            ExportArtifact(
                name="submit-job.sh",
                content=cli_script,
                artifact_type="sh",
            )
        )

        return artifacts
